<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Kuestenlogik.Bowire" Version="2.1.1" />
    <PackageReference Include="Kuestenlogik.Bowire.Protocol.Sse" Version="1.6.0" />
    <ProjectReference Include="..\Kuestenlogik.Bowire.Samples.Shared\Kuestenlogik.Bowire.Samples.Shared.csproj" />
  </ItemGroup>
</Project>
