<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Kuestenlogik.Bowire" Version="1.0.8" />
    <PackageReference Include="Kuestenlogik.Bowire.Protocol.WebSocket" Version="1.0.8" />
    <ProjectReference Include="..\Kuestenlogik.Bowire.Samples.Shared\Kuestenlogik.Bowire.Samples.Shared.csproj" />
  </ItemGroup>
</Project>
